pub(crate) mod aho_corasick;
pub(crate) mod anagram;
pub(crate) mod autocomplete_using_trie;
pub(crate) mod boyer_moore_search;
pub(crate) mod burrows_wheeler_transform;
pub(crate) mod duval_algorithm;
pub(crate) mod hamming_distance;
pub(crate) mod isogram;
pub(crate) mod isomorphism;
pub(crate) mod jaro_winkler_distance;
pub(crate) mod knuth_morris_pratt;
pub(crate) mod levenshtein_distance;
pub(crate) mod lipogram;
pub(crate) mod manacher;
pub(crate) mod palindrome;
pub(crate) mod pangram;
pub(crate) mod rabin_karp;
pub(crate) mod reverse;
pub(crate) mod run_length_encoding;
pub(crate) mod shortest_palindrome;
pub(crate) mod suffix_array;
pub(crate) mod suffix_array_manber_myers;
pub(crate) mod suffix_tree;
pub(crate) mod z_algorithm;

pub use self::aho_corasick::AhoCorasick;
pub use self::anagram::check_anagram;
pub use self::autocomplete_using_trie::Autocomplete;
pub use self::boyer_moore_search::boyer_moore_search;
pub use self::burrows_wheeler_transform::{
    burrows_wheeler_transform, inv_burrows_wheeler_transform,
};
pub use self::duval_algorithm::duval_algorithm;
pub use self::hamming_distance::hamming_distance;
pub use self::isogram::is_isogram;
pub use self::isomorphism::is_isomorphic;
pub use self::jaro_winkler_distance::jaro_winkler_distance;
pub use self::knuth_morris_pratt::knuth_morris_pratt;
pub use self::levenshtein_distance::{naive_levenshtein_distance, optimized_levenshtein_distance};
pub use self::lipogram::is_lipogram;
pub use self::manacher::manacher;
pub use self::palindrome::is_palindrome;
pub use self::pangram::is_pangram;
pub use self::pangram::PangramStatus;
pub use self::rabin_karp::rabin_karp;
pub use self::reverse::reverse;
pub use self::run_length_encoding::{run_length_decoding, run_length_encoding};
pub use self::shortest_palindrome::shortest_palindrome;
pub use self::suffix_array::generate_suffix_array;
pub use self::suffix_array_manber_myers::generate_suffix_array_manber_myers;
pub use self::suffix_tree::{Node, SuffixTree};
pub use self::z_algorithm::match_pattern;
pub use self::z_algorithm::z_array;
